spring:
  datasource:
    url: jdbc:mysql://localhost:3306/financiencia
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  seguranca:
      segredo: senha
      tempo_validade: 5

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  error:
    include-message: always
    include-binding-errors: always
  jackson:
    serialization:
      write-dates-as-timestamps: false